In [1]:
a = [10,11,12,13,14,15]

In [2]:
import numpy as np

In [3]:
n_a = np.array(a)

In [15]:
n_a

array([10, 11, 12, 13, 14, 15])

In [16]:
n_a[0]

10

In [17]:
n_a[1]

11

In [18]:
last_index = len(n_a) -1

In [19]:
n_a[last_index]

15

In [20]:
ｎ_a[-1]

15

In [21]:
ｎ_a[-2]

14

In [24]:
n_a[1:5]

array([11, 12, 13, 14])

In [25]:
np.sum(n_a)

75

In [26]:
np.max(n_a)

15

In [28]:
np.min(n_a)

10

In [29]:
np.mean(n_a)

12.5

In [30]:
rand = np.random.random(10)

In [32]:
rand

array([0.03819852, 0.50130417, 0.37723764, 0.79309775, 0.60050878,
       0.56050952, 0.40566815, 0.66040524, 0.16543177, 0.9835449 ])